### ISSUE TITLE
Flatpak support?

### ISSUE THREAD

**Issue by Gemmstone** [gottagofaster236/RewardsTheater#2]
Is it possible to add support for the flatpak version, since it's another official version of OBS for Linux, that way it's not limited to debian based distros.

**Comment by gottagofaster236** [comment]
> Is it possible to add support for the flatpak version, since it's another official version of OBS for Linux, that way it's not limited to debian based distros.

Hi, thanks for the suggestion. This is not in priority for now because there's not many Linux users, but [definitely possible](https://github.com/flathub/com.obsproject.Studio/wiki/Plugins#distributing-plugins-on-flathub) — I hope to add this in the near future.

As per [this website](https://github.com/flathub/com.obsproject.Studio/wiki/Plugins#method-2-config-folder), one can also copy .so files directly inside `~/.var/app/com.obsproject.Studio/config/obs-studio/plugins`. You can try unpacking the .deb file with dpkg-deb to get the .so out of it, and then copying it to that folder for now 😅 

I should probably consider making a PPA for the deb package as well.

**Comment by gottagofaster236** [comment]
Also, there's an [Arch repository](https://github.com/deadYokai/archrepo) with this plugin, maybe that'll be useful. (Note that I'm not the owner of the repository, though).

**Comment by Gemmstone** [comment]
> As per [this website](https://github.com/flathub/com.obsproject.Studio/wiki/Plugins#method-2-config-folder), one can also copy .so files directly inside `~/.var/app/com.obsproject.Studio/config/obs-studio/plugins`. You can try unpacking the .deb file with dpkg-deb to get the .so out of it, and then copy it to that folder as a temporary solution 😅

Hi, tried this, even copied the folder structure of another plugin, didn't work, so i'll wait until you're able to port it, no rush! 😁

**Comment by gottagofaster236** [comment]
Opened a [PR against the flathub repo](https://github.com/flathub/flathub/pull/4684), it would take some time for them to review it and then publish if everything's fine.

**Comment by gottagofaster236** [comment]
It's merged finally. You can now install the plugin via
```
flatpak install flathub com.obsproject.Studio.Plugin.RewardsTheater
```
